### ISSUE TITLE
Display actions on tile selection in Player Turn

### ISSUE THREAD

**Issue by rifo** [brdgm/joan-of-arc-orleans-solo-helper#4]
When user selects a tile, a brief text depicts available options.

Example:

Craftsman:
1 trading station / 1 coin.
Beneficial Deeds: 3, 4.
Places: Joinery (II), Goldsmith (V).

**Comment by rifo** [comment]
I prepared the code in my local branch.

**Comment by stefanseifert** [comment]
the capabilities of the tiles is depicted on the sheets as well - but if you think it's helpful to add it in the app ... can you provide your code so i can have a look? e.g. create a PR or draft PR?

**Comment by stefanseifert** [comment]
fixed with #5
